---
site:
  title: "LB1127: Unifying VMs and Containers on Red Hat OpenShift with Portworx"
  start_page: modules::index.adoc

content:
  sources:
  - url: .
    start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-summit-2025/ui-bundle.zip

    snapshot: true
  supplemental_files:
  - path: ./content/supplemental-ui

runtime:
  fetch: true

output:
  dir: ./www
